.Dd $Mdocdate: February 28 2015 $
.Dt SL 1
.Os
.Sh NAME
.Nm sl
.Nd main shared lists server
.Sh SYNOPSIS
.Nm sl
.Op Fl tv
.Op Fl p Ar port
.Sh DESCRIPTION
The
.Nm sl
program is responsible for processing new client connections and persistently
storing client and list information.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl p Ar port
Listen for connections on this port.
.It Fl t
Start server in "test" mode which uses a temporary database and a dummy
notification daemon.
.It Fl v
Print more verbose runtime information.
.El
.Sh EXIT STATUS
.Ex -std sl
.Sh SEE ALSO
.Xr prove 1 ,
.Xr cover 1
