include theos/makefiles/common.mk

APPLICATION_NAME = shlist
shlist_FILES = main.m shlistApplication.mm RootViewController.mm
shlist_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
